# Generated by Django 4.1.2 on 2024-05-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_week',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Üst', 'Üst'), ('Alt', 'Alt')], default='Normal', max_length=10),
        ),
    ]
