# Generated by Django 4.1.2 on 2024-05-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_calendar', '0002_alter_lesson_lesson_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
